apiVersion: apps/v1
kind: Deployment
metadata:
  name: casestudy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casestudy
  template:
    metadata:
      labels:
        app: casestudy
    spec:
      containers:
      - name: casestudy-container
        image: revanthv007/casestudy007
        ports:
        - containerPort: 80